### PR TITLE
Linting for shell and GitHub Actions

### PR DESCRIPTION
**Pull request by jwallwork23**
More linting!

Adds linting for shell and GitHub Actions workflows:
* https://github.com/koalaman/shellcheck
* https://woodruffw.github.io/zizmor

Also fixes an oversight in the CMake linting setup.

### CODE REVIEW

**Comment by jwallwork23** [comment]
My initial push at commit https://github.com/Cambridge-ICCS/FTorch/pull/206/commits/e128fe3a024a0c663580118091e68fba376644d4 shows the static analysis workflow failing because I'd only applied lint fixes to the `static_analysis.yml`. With my second push at commit https://github.com/Cambridge-ICCS/FTorch/pull/206/commits/5858a6be5d4e78db8523fe643145636cc932a8d0 it passes.

**Comment by jwallwork23** [comment]
#207 has been merged into the branch here so should be merged first.

**Review by jatkinson1000 — CHANGES_REQUESTED** [review]
They seem active projects.
I note zizmor is in beta, so perhaps we want to pin the version similar to fortitude, to avoid unexpected complaints.

We also need the docs updating to detail these, and I note that shellcheck is not pip installable. Seems installable via all sensible package managers. I wouldn't know where to start with Windows packaga managers, but don't see this as an issue as our docs state "follow the instructions in the linter docs".

**Comment by jwallwork23** [comment]
> They seem active projects. I note zizmor is in beta, so perhaps we want to pin the version similar to fortitude, to avoid unexpected complaints.
> 
> We also need the docs updating to detail these, and I note that shellcheck is not pip installable. Seems installable via all sensible package managers. I wouldn't know where to start with Windows packaga managers, but don't see this as an issue as our docs state "follow the instructions in the linter docs".

Thanks @jatkinson1000. Addressed in https://github.com/Cambridge-ICCS/FTorch/pull/206/commits/2834064705796bc428b4f6145dda13ffaadbaea7.

**Review by jatkinson1000 — APPROVED** [review]
Thanks @jwallwork23 All LGTM now!

**Pull request merged**
