### PR TITLE
Ensure strings end with c_null_char

### PR DESCRIPTION
**Pull request by ElliottKasoar**
See Cambridge-ICCS/FTorch-benchmarks#25

To do:

- [x] Test fixed on CSD3

### CODE REVIEW

**Comment by jatkinson1000** [comment]
A good start, perhaps need to apply `trim()` to the filename that users supply, just in case?
And do we need to handle the cases where an astute user might have already appended the null char to their filename?

**Comment by ElliottKasoar** [comment]
Thanks @jatkinson1000! I've added a trim (and adjustl, as we have in the [benchmarker_utils](https://github.com/Cambridge-ICCS/FTorch-benchmarks/blob/main/benchmarker_utils.f90#L136)).

I haven't found anything definitive to back this up, but when I discussed this with @TomMelt, my impression was that repeated null characters shouldn't be an issue, and from testing this locally, and on CSD3, this seems to be the case - running the benchmarking script as is (with a mix of `c_null_char` included and not) linked to these changes all works.

**Comment by jatkinson1000** [comment]
Yes, I think that is correct, just wanted to flag it as a point we needed to check.

**Review by jatkinson1000 — CHANGES_REQUESTED** [review]
Thanks @ElliottKasoar 

The source changes all look good, but we ought to also update the example codes to reflect these changes.

**Comment by ElliottKasoar** [comment]
Good point, thanks @jatkinson1000! I think I've removed c_null_char from all examples and the README now.

**Review by jatkinson1000 — APPROVED** [review]
C'est super! Allons-y.
Merci @ElliottKasoar

**Pull request merged**
